plugins {
    id "com.android.application"
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("keystore.properties")
def hasReleaseSigning = keystorePropertiesFile.exists()
if (hasReleaseSigning) {
    keystorePropertiesFile.withInputStream { stream ->
        keystoreProperties.load(stream)
    }
}

android {
    namespace "com.local.tiktokregion"
    compileSdk 34

    defaultConfig {
        applicationId "com.local.tiktokregion"
        minSdk 27
        targetSdk 34
        versionCode 41
        versionName "1.4.2"
    }

    signingConfigs {
        if (hasReleaseSigning) {
            release {
                storeFile rootProject.file(keystoreProperties.getProperty("storeFile"))
                storePassword keystoreProperties.getProperty("storePassword")
                keyAlias keystoreProperties.getProperty("keyAlias")
                keyPassword keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly files("libs/api-82.jar")
}
